# 机器学习基础
## NUMPY函数库基础


In [14]:
import numpy as np
from numpy import eye
a = np.array([[1,2],[3,4]])
#数组转化为矩阵
a = np.mat(np.array([[1,2],[3,4]]))
#求逆矩阵
b = a.I
a


matrix([[1, 2],
        [3, 4]])

In [15]:
b


matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])

In [16]:
a*b

matrix([[1.0000000e+00, 0.0000000e+00],
        [8.8817842e-16, 1.0000000e+00]])

In [18]:
#eye函数创建单位矩阵，消除误差值
a*b - eye(2)

matrix([[ 0.0000000e+00,  0.0000000e+00],
        [ 8.8817842e-16, -4.4408921e-16]])

# k临近算法

In [1]:
# K临近算法是分类数据最简单的算法，必须保存全部的数据集，如果数据量大的哈，需要大的存储空间，而且非常耗时

# 决策树

In [3]:
# 需要计算数据集的狄，然后选择最优方案划分数据集；matplotlib.annotations可以为图标添加注释；picklejoblib都可以保存和加载模型

# 朴树贝叶斯


In [4]:
#利用已知值来估计未知概率，例如已经职业和年龄，估计肿瘤的概率。条件概率问题：p(A|B) = p(AB)/p(B)  p(B|A) = p(AB)/p(A) 

# 逻辑回归

# 支持向量机

# AdaBoost

In [6]:
#简单的说，多个弱分类器训练成为一个强分类器。
#将一系列的弱分类器以不同的权重比组合作为最终分类选择。
#ROC曲线 横轴是假阳率，众轴代表真实阳率，面积代表概率或者准确率。